version: '3'
services:
  keycloak:
     image: jboss/keycloak:4.8.3.Final
     command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=export"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - "-Dkeycloak.migration.usersExportStrategy=REALM_FILE"
      - "-Dkeycloak.import=/opt/jboss/keycloak/Geoportal-realm.json"
     volumes:
       - ./config:/config/
       - ./startup/Geoportal-realm.json:/opt/jboss/keycloak/Geoportal-realm.json
     environment:
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=password
     ports:
       - "8843:8080"
     
